In [1]:
import pandas as pd

In [2]:
ruta_datos = 'Datos/Ejecucion_de_Actividades_Limpio.csv'

In [3]:
df = pd.read_csv(ruta_datos)

df.info()

C:\Users\acer\AppData\Local\Temp\ipykernel_6420\4131092311.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ruta_datos)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69689 entries, 0 to 69688
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   POBLACION                        69689 non-null  object
 1   NOMBREMUNICIPIO                  69689 non-null  object
 2   TERRITORIO                       69626 non-null  object
 3   DIRECCION                        68362 non-null  object
 4   TIPO PERSONAL SALUD              69689 non-null  object
 5   NUMERO AUTORIZACION              48263 non-null  object
 6   FECHA SERVICIO                   69689 non-null  object
 7   GENERO                           69689 non-null  object
 8   FEC_NAC                          69689 non-null  object
 9   EDAD                             69689 non-null  int64
 10  MOTIVO CITA / CENTRO PRODUCCION  41506 non-null  object
 11  DESCRIPCIONACTIVIDAD             69689 non-null  object
 12  CIE10                            69510 non-null  object
 13  DESCRIPCION CIE10                69510 non-null  object
 14  EMBARAZO                         69689 non-null  object
 15  Unnamed: 49                      78 non-null     object
dtypes: int64(1), object(15)
memory usage: 8.5+ MB

In [4]:
df.duplicated().sum()

np.int64(5397)

In [5]:
df = df.drop_duplicates()

In [6]:
df.isna().sum()

POBLACION                              0
NOMBREMUNICIPIO                        0
TERRITORIO                            62
DIRECCION                           1272
TIPO PERSONAL SALUD                    0
NUMERO AUTORIZACION                16170
FECHA SERVICIO                         0
GENERO                                 0
FEC_NAC                                0
EDAD                                   0
MOTIVO CITA / CENTRO PRODUCCION    22821
DESCRIPCIONACTIVIDAD                   0
CIE10                                179
DESCRIPCION CIE10                    179
EMBARAZO                               0
Unnamed: 49                        64214
dtype: int64

In [235]:
df.head(2)

,POBLACION,NOMBREMUNICIPIO,TERRITORIO,DIRECCION,TIPO PERSONAL SALUD,NUMERO AUTORIZACION,FECHA SERVICIO,GENERO,FEC_NAC,EDAD,MOTIVO CITA / CENTRO PRODUCCION,DESCRIPCIONACTIVIDAD,CIE10,DESCRIPCION CIE10,EMBARAZO,Unnamed: 49
0,SUBSIDIADO - CAUCA,ALMAGUER,CAQUIONA,ALBERGUE RAISES NASAS - CENTRO (POPAYAN),ADMINISTRATIVO,1477016,31/01/2025,F,15/10/1963,61,NaN,TRASLADO ASISTENCIAL BASICO TERRESTRE SECUNDAR...,Y848,OTROS PROCEDIMIENTOS MEDICOS,NO,13/02/2025 3.04 PM
1,SUBSIDIADO - CAUCA,ALMAGUER,CAQUIONA,ALBERGUE RAISES NASAS - CENTRO (POPAYAN),ADMINISTRATIVO,1463208,31/01/2025,F,15/10/1963,61,NaN,TRASLADO ASISTENCIAL BASICO TERRESTRE SECUNDAR...,Y848,OTROS PROCEDIMIENTOS MEDICOS,NO,13/02/2025 4.43 PM

In [236]:
df['TIPO PERSONAL SALUD'].value_counts()

TIPO PERSONAL SALUD
CASA DE PASO POPAYAN                               9738
GINECOLOGIA Y OBSTETRICIA                          4438
ADMINISTRATIVO                                     4178
RADIOLOGIA                                         3585
CASA DE PASO CALI                                  3495
OFTALMOLOGIA                                       3112
FISIOTERAPEUTA                                     2720
MEDICINA INTERNA                                   2498
PEDIATRIA                                          2362
CARDIOLOGIA                                        2248
RETINOLOGIA                                        2210
DERMATOLOGIA                                       2057
MEDICINA MATERNO FETAL                             1703
NUTRICIONISTA                                      1670
PSICOTERAPITA INDIVIDUAL POR PSICOLOGIA            1592
FONOAUDIOLOGIA                                     1562
OTORRINOLARINGOLOGIA                               1477
ORTOPEDIA Y TRAUMATOLOGIA                          1406
FISIATRIA                                          1144
GASTROENTEROLOGIA                                  1093
NEUROLOGIA                                         1076
HOMEOPATIA                                          987
UROLOGIA                                            901
CIRUGIA GENERAL                                     870
NEFROLOGIA                                          629
INMUNOLOGIA                                         627
DOLOR Y CUIDADOS PALEATIVOS                         565
TERAPIA OCUPACIONAL                                 531
NEUROPSICOLOGIA                                     497
CASA DE PASO LA PLATA                               456
NEUROLOGIA PEDIATRICA                               406
CIRUGIA VASCULAR Y ANGIOLOGIA                       391
PSIQUIATRIA                                         358
CIRUGIA DE LA MAMA Y TUMORES DE TEJIDOS BLANDOS     348
TRABAJADORA SOCIAL                                  328
REUMATOLOGIA                                        258
ENDOCRINOLOGIA                                      198
PROFESIONAL DE ENFERMERIA                           177
GASTROENTEROLOGIA PEDIATRICA                        129
MEDICO TRADICIONAL                                   75
INFECTOLOGIA PEDIATRICA                              70
MEDICINA FAMILIAR                                    67
AUXILIAR ENFERMERIA                                  60
Name: count, dtype: int64

In [237]:
df[df['TIPO PERSONAL SALUD'] == 'ADMINISTRATIVO'].isnull().sum()

POBLACION                             0
NOMBREMUNICIPIO                       0
TERRITORIO                            0
DIRECCION                            38
TIPO PERSONAL SALUD                   0
NUMERO AUTORIZACION                  51
FECHA SERVICIO                        0
GENERO                                0
FEC_NAC                               0
EDAD                                  0
MOTIVO CITA / CENTRO PRODUCCION    4159
DESCRIPCIONACTIVIDAD                  0
CIE10                                77
DESCRIPCION CIE10                    77
EMBARAZO                              0
Unnamed: 49                        4100
dtype: int64

In [238]:
df_adminitrraticos = df[df['TIPO PERSONAL SALUD'] == 'ADMINISTRATIVO']
df_adminitrraticos['MOTIVO CITA / CENTRO PRODUCCION'].value_counts()

MOTIVO CITA / CENTRO PRODUCCION
112-RETINOLOGIA- CONTROL    19
Name: count, dtype: int64

In [7]:
df = df.drop(columns=['Unnamed: 49','NUMERO AUTORIZACION','DIRECCION', ])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64292 entries, 0 to 69688
Data columns (total 13 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   POBLACION                        64292 non-null  object
 1   NOMBREMUNICIPIO                  64292 non-null  object
 2   TERRITORIO                       64230 non-null  object
 3   TIPO PERSONAL SALUD              64292 non-null  object
 4   FECHA SERVICIO                   64292 non-null  object
 5   GENERO                           64292 non-null  object
 6   FEC_NAC                          64292 non-null  object
 7   EDAD                             64292 non-null  int64
 8   MOTIVO CITA / CENTRO PRODUCCION  41471 non-null  object
 9   DESCRIPCIONACTIVIDAD             64292 non-null  object
 10  CIE10                            64113 non-null  object
 11  DESCRIPCION CIE10                64113 non-null  object
 12  EMBARAZO                         64292 non-null  object
dtypes: int64(1), object(12)
memory usage: 6.9+ MB

In [240]:
df.isna().sum()

POBLACION                              0
NOMBREMUNICIPIO                        0
TERRITORIO                            62
TIPO PERSONAL SALUD                    0
FECHA SERVICIO                         0
GENERO                                 0
FEC_NAC                                0
EDAD                                   0
MOTIVO CITA / CENTRO PRODUCCION    22821
DESCRIPCIONACTIVIDAD                   0
CIE10                                179
DESCRIPCION CIE10                    179
EMBARAZO                               0
dtype: int64

In [9]:
df_final_v1 = df.drop(columns=['MOTIVO CITA / CENTRO PRODUCCION'])
df_final_v1.dropna()
df_final_v1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64292 entries, 0 to 69688
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   POBLACION             64292 non-null  object
 1   NOMBREMUNICIPIO       64292 non-null  object
 2   TERRITORIO            64230 non-null  object
 3   TIPO PERSONAL SALUD   64292 non-null  object
 4   FECHA SERVICIO        64292 non-null  object
 5   GENERO                64292 non-null  object
 6   FEC_NAC               64292 non-null  object
 7   EDAD                  64292 non-null  int64
 8   DESCRIPCIONACTIVIDAD  64292 non-null  object
 9   CIE10                 64113 non-null  object
 10  DESCRIPCION CIE10     64113 non-null  object
 11  EMBARAZO              64292 non-null  object
dtypes: int64(1), object(11)
memory usage: 6.4+ MB

In [10]:
df_final_v1 = df_final_v1.drop(columns=['FECHA SERVICIO'])

In [243]:
df_final_v1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64292 entries, 0 to 69688
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   POBLACION             64292 non-null  object
 1   NOMBREMUNICIPIO       64292 non-null  object
 2   TERRITORIO            64230 non-null  object
 3   TIPO PERSONAL SALUD   64292 non-null  object
 4   GENERO                64292 non-null  object
 5   FEC_NAC               64292 non-null  object
 6   EDAD                  64292 non-null  int64
 7   DESCRIPCIONACTIVIDAD  64292 non-null  object
 8   CIE10                 64113 non-null  object
 9   DESCRIPCION CIE10     64113 non-null  object
 10  EMBARAZO              64292 non-null  object
dtypes: int64(1), object(10)
memory usage: 5.9+ MB

In [11]:
# converir columna de fechas en tipi de datoa datatime

df_final_v1['FEC_NAC'] = pd.to_datetime(df_final_v1['FEC_NAC'])

df_final_v1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64292 entries, 0 to 69688
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   POBLACION             64292 non-null  object
 1   NOMBREMUNICIPIO       64292 non-null  object
 2   TERRITORIO            64230 non-null  object
 3   TIPO PERSONAL SALUD   64292 non-null  object
 4   GENERO                64292 non-null  object
 5   FEC_NAC               64292 non-null  datetime64[ns]
 6   EDAD                  64292 non-null  int64
 7   DESCRIPCIONACTIVIDAD  64292 non-null  object
 8   CIE10                 64113 non-null  object
 9   DESCRIPCION CIE10     64113 non-null  object
 10  EMBARAZO              64292 non-null  object
dtypes: datetime64[ns](1), int64(1), object(9)
memory usage: 5.9+ MB

C:\Users\acer\AppData\Local\Temp\ipykernel_6420\3212544448.py:3: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_final_v1['FEC_NAC'] = pd.to_datetime(df_final_v1['FEC_NAC'])

In [12]:
# de columnas de fechas lo que se hace es extraer el año y el mes de la fecha y gregarlas al dataframe
# en columnas independientes

df_final_v1['Año Nac'] = df_final_v1['FEC_NAC'].dt.year
df_final_v1['Mes Nac'] = df_final_v1['FEC_NAC'].dt.month

df_final_v1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64292 entries, 0 to 69688
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   POBLACION             64292 non-null  object
 1   NOMBREMUNICIPIO       64292 non-null  object
 2   TERRITORIO            64230 non-null  object
 3   TIPO PERSONAL SALUD   64292 non-null  object
 4   GENERO                64292 non-null  object
 5   FEC_NAC               64292 non-null  datetime64[ns]
 6   EDAD                  64292 non-null  int64
 7   DESCRIPCIONACTIVIDAD  64292 non-null  object
 8   CIE10                 64113 non-null  object
 9   DESCRIPCION CIE10     64113 non-null  object
 10  EMBARAZO              64292 non-null  object
 11  Año Nac               64292 non-null  int32
 12  Mes Nac               64292 non-null  int32
dtypes: datetime64[ns](1), int32(2), int64(1), object(9)
memory usage: 6.4+ MB

In [246]:
# mi variable objetivo es categoria por lo cual re analisa el comportamiento dee stas categorias

variable_obt_categorias = df_final_v1['CIE10'].value_counts()

In [247]:
# se nota que la variable objetivo esta desbalanceada sobre todo por el codigo Y848 el cual tiene 21716 registros
# si se queire balancear se recomendaria seleecioanr aleatoriamente 1500 registro unicamwente con ese codigo.
variable_obt_categorias

CIE10
Y848    21716
I10X     1360
Z349     1316
N189     1007
Z359     1001
        ...
R230        1
I479        1
C679        1
Q039        1
I131        1
Name: count, Length: 2031, dtype: int64

In [248]:
variable_obt_categorias.shape

(2031,)

In [249]:
df_final_v1 = df_final_v1.drop(columns= ['DESCRIPCION CIE10'])
df_final_v1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64292 entries, 0 to 69688
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   POBLACION             64292 non-null  object
 1   NOMBREMUNICIPIO       64292 non-null  object
 2   TERRITORIO            64230 non-null  object
 3   TIPO PERSONAL SALUD   64292 non-null  object
 4   GENERO                64292 non-null  object
 5   FEC_NAC               64292 non-null  datetime64[ns]
 6   EDAD                  64292 non-null  int64
 7   DESCRIPCIONACTIVIDAD  64292 non-null  object
 8   CIE10                 64113 non-null  object
 9   EMBARAZO              64292 non-null  object
 10  Año Nac               64292 non-null  int32
 11  Mes Nac               64292 non-null  int32
dtypes: datetime64[ns](1), int32(2), int64(1), object(8)
memory usage: 5.9+ MB

# Preprocesar datos

Esta seccion preprocesa los datos de columnas categoricas y los transforma a valores numericos por medio de la estrategia label encoder de sckit-learn.

In [14]:
from sklearn.preprocessing import LabelEncoder # tranfromar datosd categoricos en numeros enteros
import joblib

In [15]:
colum_pre = df_final_v1.select_dtypes('object').columns

colum_pre

Index(['POBLACION', 'NOMBREMUNICIPIO', 'TERRITORIO', 'TIPO PERSONAL SALUD',
       'GENERO', 'DESCRIPCIONACTIVIDAD', 'CIE10', 'DESCRIPCION CIE10',
       'EMBARAZO'],
      dtype='object')

In [16]:
for columna in colum_pre:
    print(columna)

POBLACION
NOMBREMUNICIPIO
TERRITORIO
TIPO PERSONAL SALUD
GENERO
DESCRIPCIONACTIVIDAD
CIE10
DESCRIPCION CIE10
EMBARAZO

In [17]:
import json
# Aplicar label encoder en todas als columans categoricas o typo object
json_encoder = {}

for columna in colum_pre:
    columna_interes = df_final_v1[columna]
    encoder = LabelEncoder()

    encoder.fit(columna_interes)

    mapeo_categorias= dict(zip(encoder.classes_, encoder.transform(encoder.classes_)))
    # Solución 1: Convertir los valores a int nativo de Python
    # Iteramos sobre los valores del diccionario y los convertimos a int
    mapeo_categorias_limpio = {k: int(v) for k, v in mapeo_categorias.items()}
    # usar encoder para tranfromar categoria de columna de interes
    colum_tran = encoder.transform(columna_interes)

    df_final_v1[columna+'_encoder'] = colum_tran

    json_encoder[columna]= mapeo_categorias_limpio

# guadarmso el json_encoder en un json 
# Nombre del archivo donde se guardará el JSON
nombre_archivo = 'Encoders/mapeo_encoders.json'

# Usamos 'with' para garantizar que el archivo se cierre correctamente
with open(nombre_archivo, 'w') as f:
    json.dump(json_encoder, f, indent=4)


df_final_v1.head(2)

,POBLACION,NOMBREMUNICIPIO,TERRITORIO,TIPO PERSONAL SALUD,GENERO,FEC_NAC,EDAD,DESCRIPCIONACTIVIDAD,CIE10,DESCRIPCION CIE10,...,Mes Nac,POBLACION_encoder,NOMBREMUNICIPIO_encoder,TERRITORIO_encoder,TIPO PERSONAL SALUD_encoder,GENERO_encoder,DESCRIPCIONACTIVIDAD_encoder,CIE10_encoder,DESCRIPCION CIE10_encoder,EMBARAZO_encoder
0,SUBSIDIADO - CAUCA,ALMAGUER,CAQUIONA,ADMINISTRATIVO,F,1963-10-15,61,TRASLADO ASISTENCIAL BASICO TERRESTRE SECUNDAR...,Y848,OTROS PROCEDIMIENTOS MEDICOS,...,10,1,2,21,0,0,336,1932,1272,0
1,SUBSIDIADO - CAUCA,ALMAGUER,CAQUIONA,ADMINISTRATIVO,F,1963-10-15,61,TRASLADO ASISTENCIAL BASICO TERRESTRE SECUNDAR...,Y848,OTROS PROCEDIMIENTOS MEDICOS,...,10,1,2,21,0,0,336,1932,1272,0

In [18]:
df_final_v1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64292 entries, 0 to 69688
Data columns (total 22 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   POBLACION                     64292 non-null  object
 1   NOMBREMUNICIPIO               64292 non-null  object
 2   TERRITORIO                    64230 non-null  object
 3   TIPO PERSONAL SALUD           64292 non-null  object
 4   GENERO                        64292 non-null  object
 5   FEC_NAC                       64292 non-null  datetime64[ns]
 6   EDAD                          64292 non-null  int64
 7   DESCRIPCIONACTIVIDAD          64292 non-null  object
 8   CIE10                         64113 non-null  object
 9   DESCRIPCION CIE10             64113 non-null  object
 10  EMBARAZO                      64292 non-null  object
 11  Año Nac                       64292 non-null  int32
 12  Mes Nac                       64292 non-null  int32
 13  POBLACION_encoder             64292 non-null  int64
 14  NOMBREMUNICIPIO_encoder       64292 non-null  int64
 15  TERRITORIO_encoder            64292 non-null  int64
 16  TIPO PERSONAL SALUD_encoder   64292 non-null  int64
 17  GENERO_encoder                64292 non-null  int64
 18  DESCRIPCIONACTIVIDAD_encoder  64292 non-null  int64
 19  CIE10_encoder                 64292 non-null  int64
 20  DESCRIPCION CIE10_encoder     64292 non-null  int64
 21  EMBARAZO_encoder              64292 non-null  int64
dtypes: datetime64[ns](1), int32(2), int64(10), object(9)
memory usage: 10.8+ MB

In [19]:
# con la estrategia aplicada seleecionamos la columnas con ls que se va a entrenar relamente
# si necesitan incluir ms tipos de datos utilizar la propiedad include=['int', 'float'] dentro de select.types()
df_listo = df_final_v1.select_dtypes('int')
df_listo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64292 entries, 0 to 69688
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   EDAD                          64292 non-null  int64
 1   Año Nac                       64292 non-null  int32
 2   Mes Nac                       64292 non-null  int32
 3   POBLACION_encoder             64292 non-null  int64
 4   NOMBREMUNICIPIO_encoder       64292 non-null  int64
 5   TERRITORIO_encoder            64292 non-null  int64
 6   TIPO PERSONAL SALUD_encoder   64292 non-null  int64
 7   GENERO_encoder                64292 non-null  int64
 8   DESCRIPCIONACTIVIDAD_encoder  64292 non-null  int64
 9   CIE10_encoder                 64292 non-null  int64
 10  DESCRIPCION CIE10_encoder     64292 non-null  int64
 11  EMBARAZO_encoder              64292 non-null  int64
dtypes: int32(2), int64(10)
memory usage: 5.9 MB

In [20]:
df_listo.to_csv('Datos/Datos_Clinicos_Listos.csv', index=False)

In [256]:
# selecionar variable opbejto y vriable independitnes es lo que llaamremos 
# matriz x = independientes 
# vector y =  dependiente

X = df_listo.drop(columns=['CIE10_encoder']) # se elimina la vairbale objetivo y se genera la matriz X

y = df_listo['CIE10_encoder'] # solo se toma la viable objetivo

In [257]:
# corte de datos en entrenamiento y prueba de modelos

from sklearn.model_selection import train_test_split

# División del conjutno de datos en entrenamiento y prueba

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.9, random_state= 42 )

print('Conjunto de datos de entrada de entrenamiento X_train:', X_train.shape)
print('Conjunto de datos de salida de entrenamiento y_train:', y_train.shape)

print('Conjunto de datos de entrada de prueba X_test:', X_test.shape)
print('Conjunto de datos de salida de prueba y_test:', y_test.shape)

Conjunto de datos de entrada de entrenamiento X_train: (6429, 10)
Conjunto de datos de salida de entrenamiento y_train: (6429,)
Conjunto de datos de entrada de prueba X_test: (57863, 10)
Conjunto de datos de salida de prueba y_test: (57863,)

# Entrenamiento del modelo con random forest 

Est eccion muetsra comousar los datos para entrenar un modleo tipo randon forest

In [258]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.tree import DecisionTreeClassifier

model_rfc = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)# Entrenar modelo de machine learning
model_dt = DecisionTreeClassifier()

In [ ]:
# Entrenar model DecisionTreeClassifier()

model_dt.fit(X_train, y_train)

y_pred_dt = model_dt.predict(X_test)

accuracy_dt = accuracy_score( y_test, y_pred_dt)

print('Exactitud del modelo DecisionTreeClassifier = ', accuracy_dt)

In [ ]:
# Entrenar model RandomForestClassifier

model_rfc.fit(X_train, y_train)

y_pred_dt_3 = model_rfc.predict(X_test)

accuracy_dt_3 = accuracy_score( y_test, y_pred_dt_3)

print('Exactitud del modelo RandomForestClassifier = ', accuracy_dt_3)